Feat: add additional output for cloudfront bucket
philips-software/terraform-aws-cloudfront-s3 pull request #9
Opened 2019-09-25 12:51 UTC by pharindoko

2019-09-25 13:07 UTC, pharindoko commented
I need at least the bucket id as I want to use codepipeline and codebuild to update sources:
aws s3 sync s3://bucket_name

2019-09-26 06:13 UTC, mpas commented
@pharindoko Thanks for the contribution, will check today!

2019-10-04 21:39 UTC, pharindoko commented
Hey Marco, can you please check my PR ?

2019-10-09 20:19 UTC, npalm commented
@mpas did you had time to have a look? Otherwise iI can take over the review.  @pharindoko sorry for the delay

2019-10-16 11:49 UTC, pharindoko commented
Hey guys, any update on this ?

2019-10-21 05:20 UTC, mpas requested changes

2019-10-21 05:20 UTC, mpas commented on output.tf
> +output "cloudfront_bucket" {
Please keep the original name for backwards compatabilty "cloudfront_bucket_arn". A suggestion is to return a new output with a return value of the whole resource "cloudfront_bucket" then all variables are returned and usable.

2019-10-21 22:19 UTC, pharindoko reviewed
Fine

2019-10-23 21:30 UTC, pharindoko commented
@mpas 
This can be merged or do you expect me to change something in addition ?

2019-10-23 21:35 UTC, npalm commented
@mpas looks good to me, can you check the change?

2021-01-14 12:18 UTC, npalm approved these changes

2021-01-14 12:40 UTC, npalm approved these changes

2021-01-14 12:41 UTC, merged